export const presetServiceCategories: string[] = [
    "Home",
    "Office",
    "Automotive",
    "Event",
    "Commercial",
    "Industrial",
    "Retail",
    "Hospitality",
    "Healthcare",
    "Educational",
    "Outdoor & Garden",
    "Moving & Relocation",
    "Specialty Cleaning",
    "Maintenance & Repair",
    "Organization",
    "Seasonal",
    "Tech & Electronics",
    "Marine",
    "Aviation",
]

export const presetServiceNames: string[] = [
    "Fan Cleaning",
    "Carpet Washing",
    "Floor Mopping",
    "Window Cleaning",
    "Bathroom Sanitization",
    "Kitchen Deep Cleaning",
    "Wall Stain Removal",
    "Carpet Vacuuming",
    "Conference Room Cleaning",
    "Trash Removal",
    "Air Vent Cleaning",
    "Device Dusting",
    "Post-event Cleanup",
    "Catering Area Cleanup",
    "Trash Disposal",
    "Car Washing",
    "Tire Polishing",
    "Interior Vacuuming",
    "Windshield Cleaning",
    "Headlight Cleaning",
    "Wheel Rim Cleaning",
    "Dashboard Cleaning",
    "Fireplace & Chimney Cleaning (Visual Inspection Prep)",
    "Pet Hair Removal Service",
    "Post-Renovation Cleaning",
    "Move-In Cleaning",
    "Move-Out Cleaning",
    "Spring Cleaning Service",
    "Fall Cleaning Service",
    "Holiday Prep Cleaning",
    "Hoarding Situation Cleanup",
    "Biohazard Remediation Cleaning",
    "Crime Scene Cleanup (Requires Certification)",
    "Trauma Scene Cleanup (Requires Certification)",
    "Mold Remediation Support Cleaning",
    "Water Damage Cleanup Support",
    "Fire & Smoke Damage Cleanup Support",
    "Air Duct Cleaning",
    "Dryer Vent Cleaning",
    "Industrial Equipment Degreasing",
    "Heavy-Duty Machinery Cleaning",
    "Graffiti Removal",
    "Construction Site Final Clean",
    "Hard Hat Area Cleaning",
    "Computer Keyboard & Mouse Cleaning",
    "Monitor Screen Cleaning",
    "Computer Tower Dusting (Exterior)",
    "Laptop Cleaning",
    "Peripheral Device Cleaning (Printer, Scanner)",
    "Cable Management & Tidying",
    "Home Theater Equipment Dusting",
    "Gaming Console Cleaning",
    "Guest Room Turnover Cleaning",
    "Home Sanitization & Disinfection Service",
    "Allergen Reduction Cleaning",
    "Eco-Friendly / Green Cleaning",
    "Home Decluttering Service",
    "Closet Organization",
    "Pantry Organization",
    "Kitchen Cabinet Organization",
    "Garage Organization & Cleanup",
    "Basement Organization & Cleanup",
    "Home Office Organization",
    "Paper & File Management",
    "Toy Room Organization",
    "Storage Unit Organization",
    "General Office Cleaning",
    "Commercial Building Cleaning",
    "Retail Store Cleaning",
    "Restaurant Cleaning (Front of House)",
    "Restaurant Kitchen Deep Cleaning & Degreasing",
    "Hotel Room Cleaning / Turnover",
    "Common Area Cleaning (Lobby, Hallways)",
    "Premium Car Wash & Wax",
    "Exterior Car Detailing",
    "Interior Car Detailing",
    "Complete Car Detailing",
    "Interior Surface Sanitization (Car)",
    "Headliner Cleaning (Car)",
    "Trunk Cleaning",
    "Engine Bay Cleaning",
    "Undercarriage Wash",
    "Glass Treatment / Rain Repellent Application",
    "Paint Correction / Swirl Removal",
    "Clay Bar Treatment",
    "Ceramic Coating Application",
    "Odor Elimination (Car)",
    "Pet Hair Removal (Car)",
    "Motorcycle Washing & Detailing",
    "RV / Motorhome Washing & Detailing (Interior/Exterior)",
    "Boat Washing & Waxing",
    "Boat Interior Cleaning / Detailing",
    "Yacht Cleaning Services",
    "Small Aircraft Exterior Wash",
    "Aircraft Interior Cleaning",
    "Lawn Mowing & Edging",
    "Hedge & Shrub Trimming",
    "Weed Control Service",
    "Leaf Removal / Yard Cleanup",
    "Garden Bed Maintenance",
    "Mulch Installation",
    "Flower Planting",
    "Gutter Cleaning",
    "Downspout Flushing",
    "Pressure Washing (Siding, Walls)",
    "Driveway Pressure Washing",
    "Sidewalk Pressure Washing",
    "Patio & Deck Pressure Washing",
    "Fence Pressure Washing",
    "Deck Cleaning & Staining/Sealing",
    "Fence Cleaning & Staining/Sealing",
    "Outdoor Furniture Cleaning",
    "Grill / BBQ Cleaning",
    "Pool Deck Cleaning",
    "Pool Tile Cleaning",
    "Hot Tub / Spa Cleaning",
    "Exterior Window Washing",
    "Screen Door & Window Screen Cleaning",
    "Garage Door Cleaning",
    "Roof Moss Removal (Gentle Methods)",
    "Solar Panel Cleaning",
    "Yard Waste Removal",
    "Sprinkler Head Check & Cleaning",
]

